uwpokerclub/api

internal/models/semester.go, internal/services/events_service_test.go, internal/services/membership_service.go, internal/services/semester_service.go, internal/services/semester_service_test.go, internal/services/transaction_service_test.go, internal/testhelpers/helpers.go, migrations/20220703231444_initialize_database.sql
Closes uwpokerclub/tickets#197
=> ticket/197: fixing field name on semester

internal/services/events_service.go, internal/services/events_service_test.go
Closes uwpokerclub/tickets#200
=> ticket/200: sign out unsigned out members in last place

migrations/20230824124339_add_structures_and_blinds.sql
Adds a new migration to add two new tables:
- `blinds`
- `structures`
Also adds a new column `structure_id` to the `events` table that is a reference to the structures table.
Closes #194
=> Add a migration for structures and blinds

internal/models/event.go, internal/services/events_service.go, internal/services/events_service_test.go, internal/testhelpers/helpers.go
Adds support for structures on events by adding a `StructureID` field on the `Events` model and updates each event handler to return this information. 
Also I have updated the test file to use the new prefered formatting.
Closes #201
=> feat(events): add structure support to events

internal/models/event.go, internal/models/participant.go, internal/server/events_handler.go, internal/server/participants_handler.go, internal/server/server.go, internal/services/events_service.go, internal/services/events_service_test.go, internal/services/participants_service.go, internal/services/participants_service_test.go, internal/testhelpers/helpers.go, migrations/20230904172933_move_rebuy_to_events.sql
Moves the `rebuys` field from `participants` to `events` so it is now a "global" count of the rebuys across an event instead of a count of an individual person's rebuys.
Closes #202
**BREAKING CHANGE**: Removes the rebuy route on participants, and adds a new route on events as a replacement
=> feat(events): move rebuys from participants to events

internal/models/event.go, internal/services/events_service.go
Fixes the event entry count not showing on the event list due to an incorrect type being used to scan the DB results.
Fixes #203
=> fix(events): use ListEventsResponse type to capture event entry count

internal/models/event.go, internal/services/events_service.go, internal/services/events_service_test.go, internal/services/points_service.go, internal/services/points_service_test.go, internal/testhelpers/helpers.go, migrations/20230905184942_add_points_multiplier_to_events.sql
Adds a new column to `events` called `points_multiplier`. Updates the calculate points function to use this multiplier in the final step of calculating the points for an event.
Closes #205
=> feat(events): add a points multiplier to events

internal/models/structures.go
Fixes an issue where validation was not allowing blind levels with an ante of `0`.
Fixes #218
=> fix(structures): allow ante of 0 in create request

internal/server/events_handler.go, internal/server/server.go, internal/services/events_service.go, internal/services/events_service_test.go
Adds a new API route that allows users to un-end an event. This will just undo any points given so executive members can fix the standings of events.
Closes #216
=> feat(events): add support for un-ending events

migrations/20231019144616_update_all_event_structures.sql
Fixes an error when ending or restarting event which was caused by events that did not have `structure_id` set. This fix creates a new migration that will update all of these events and give them the structure with `id: 1`.
Fixes #228
=> fix(events): update events with no structure to fix update error

.github/workflows/publish.yml
Adds a new job to the publish CI that automatically deploys the new version to the Google Cloud Run service.
Closes #230
=> build(cd): setup auto deploy to production

internal/middleware/cors.go
Updates the CORS policy to allow requests from the new localhost app port when in local development.
Closes #247
=> fix(cors): update cors policy to allow new app endpoint

Dockerfile, docker-compose.yml, go.mod
Updates the minimum go version to 1.21, and updates the Dockerfile to pull the go 1.21.10-buster image.
Closes #221
=> build: update go version to 1.21

migrations/20240605010637_add_sessions_table.sql
Creates a new migration that adds the `sessions` table.
Closes #272
=> feat: create new table for sessions

internal/authentication/session_manager.go, internal/authentication/session_manager_test.go, internal/server/authentication_handler.go, internal/server/server.go
Added route for API users to invalidate their own sessions. Updated unit
tests to cover this new functionality.
Closes #274
=> Add session logout route

internal/authentication/session_manager.go, internal/authentication/session_manager_test.go, internal/middleware/authentication.go, internal/server/server.go
Updates the UseAuthentication middleware to add optional support for
session based authentication. The old JWT based authentication is still
in the middleware, and will be removed once the webapp has been updated
to support session based authentication.
Closes #275
=> Modify UseAuthentication middleware to support sessions

.github/workflows/ci.yml, cmd/start.go, cron/session_cleanup.go, cron/session_cleanup_test.go, go.mod, go.sum
Implements the cron package to start a daily cron task that will remove
all expired sessions from the database.
Closes #279
=> Add session cleanup cron task

cmd/start.go, docker-compose.yml, internal/models/membership.go, internal/server/memberships_handler.go, internal/services/membership_service.go, internal/services/membership_service_test.go
This PR implements `limit` and `offset` query parameters to the list memberships route. These parameters are optional, so if they are not present in the query parameters, this endpoint will perform the existing functionality of returning all members. This is to ensure backwards compatibility with the app while the pagination component is worked on. Also, I've updated the docker-compose file to support debugging with delve, making all our debugging lives easier.
Closes #309
=> Add pagination parameters to the list memberships route

internal/server/memberships_handler.go
This PR adds check for the pagination parameters in the list memberships route ensuring they are within a valid range. If not they will default.
Fixes #309
=> Add check for pagination parameters

cmd/start.go, internal/database/driver.go
This commit fixes a major security issue of SQL queries being leaked to
the console. This is because by default the GORM logger is set to log
when a query errors (i.e. a record is not found). We are turning this
down to silent and removing the check on startup to log all queries for
local development.
Fixes #323
=> fix: silence DB logs by default

internal/models/user.go, internal/server/users_handler.go, internal/services/user_service.go, internal/services/user_service_test.go
This adds support for new query parameters on the list users endpoint to filter the list of users. The new supported query parameters are `id,name,email,faculty`. Both `id` and `faculty` filter on exact matches. `name` and `email` both filter on partial matches, similar to searching.
Closes #195
=> feat: implement filter query parameters on list users endpoint

internal/models/user.go, internal/server/semesters_handler.go, internal/server/server.go, internal/services/semester_service.go, internal/services/semester_service_test.go
Implements a new route on the semesters API to export the top 100
rankings as CSV.
Closes #321
=> feat: create route to export top 100 rankings as a CSV

Makefile, internal/models/event.go, internal/server/events_handler.go, internal/server/server.go, internal/services/events_service.go, internal/services/events_service_test.go
Implements a new route in the Events API that allows the requester to update an events name, format, notes, start date, and points multiplier.
Closes #191
=> feat(events): add route to event API to update events
