uwpokerclub/api

.eslintrc.json, src/middleware/authenticate.js, src/routes/api.js, src/routes/users.js
=> uwp-24: adding users api route

src/routes/api.js, src/routes/events.js, src/routes/users.js
=> uwp-27: creating event routes

src/routes/api.js, src/routes/participants.js
=> uwp-28: creating participants route

src/routes/participants.js, src/routes/semesters.js
=> uwp-29: fixing various things

src/routes/semesters.js
=> uwp-39: fixing query error on list semesters

src/routes/users.js
=> uwp-40: fixing error in export route

README.md, src/routes/events.js, src/routes/participants.js, src/routes/semesters.js
=> uwp-52: Added users info to participants endpoint

docker-compose.yml, src/index.ts, src/routes/participants.ts
=> uwp-8: fixing ordering of participants when signed_out_at field is null

.github/dependabot.yml, .github/workflows/ci.yml, jest.config.js, package-lock.json, package.json, src/lib/environment/EnvironmentChecker.ts
=> uwp-64: adding Github actions to build and run tests

docker-compose.yml, migrations/1620598566624_adding-membership-table.js, src/lib/server/Server.ts, src/routes/api.ts, src/routes/events.ts, src/routes/memberships.ts, src/routes/participants.ts, src/routes/users.ts, src/tasks/calculate_past_entrant_points.ts, src/types/entry.d.ts, src/types/index.d.ts, src/types/membership.d.ts, src/types/ranking.d.ts, src/types/user.d.ts, tsconfig.json
- uwp-72: creating migration, fixing existing routes
- uwp-72: adding new membership route
Closes uwpokerclub/tickets#72
=> uwp-72: implementing membership api

.prettierrc.json, docker-compose.yml, package-lock.json, package.json, src/index.ts, src/routes/semesters.ts, src/tasks/calculate_past_entrant_points.ts
References uwpokerclub/tickets#107
=> uwp/107: Adding SSL connection options to PG pool

.prettierignore, package-lock.json, src/routes/semesters.ts, src/types/index.d.ts, src/types/transaction.d.ts
=> uwp/77: adding the transactions api

src/routes/events.ts, src/routes/participants.ts, src/types/entry.d.ts
=> uwp/80: adding rebuys field to participants api

src/routes/events.ts, src/routes/login.ts, src/routes/participants.ts, src/routes/semesters.ts, src/routes/users.ts
Closes uwpokerclub/tickets#113
=> uwp/113: close db client on api error

src/routes/memberships.ts, src/types/membership.d.ts
=> uwp/79: adding discounted field to membership endpoints

src/routes/semesters.ts, src/types/semester.d.ts
=> uwp/78: adding new fields to create semester route

.eslintrc.json, src/routes/memberships.ts, src/routes/participants.ts
=> uwp/81: trigger current budget update on new actions

.eslintrc.json, .gitignore, .prettierignore, docker-compose.yml, migrations/1649034471171_semester-budget-tracking.js, package-lock.json, src/routes/events.ts, src/routes/memberships.ts, src/routes/participants.ts, src/routes/semesters.ts, src/types/entry.d.ts, src/types/index.d.ts, src/types/membership.d.ts, src/types/semester.d.ts, src/types/transaction.d.ts
=> uwp/75: implementing semester budget tracking

src/routes/memberships.ts, src/routes/semesters.ts
Closes uwpokerclub/tickets#126
=> tickets/126: adding more actions for budget updating

src/routes/memberships.ts
Closes uwpokerclub/tickets#136
=> tickets/136: sorting membership list alphabetically

src/routes/memberships.ts
Closes uwpokerclub/tickets#165
=> tickets/165: updating list membership query to include event attendance count

src/routes/memberships.ts
=> Revert "tickets/165: updating list membership query to include event attendance count"

src/routes/memberships.ts
Closes uwpokerclub/tickets#165
=> tickets/165: adding attendance to membership list

internal/server/authentication_handler.go, internal/server/events_handler.go, internal/server/memberships_handler.go, internal/server/participants_handler.go, internal/server/semesters_handler.go, internal/server/server.go, internal/server/transactions_handler.go, internal/server/users_handler.go
Closes uwpokerclub/tickets#198
=> tickets/198: refactoring route definition and implementation

internal/server/memberships_handler.go, migrations/20230118151719_add_user_semester_uniqueness_constraint.sql
Closes uwpokerclub/tickets#201
=> ticket/201: adding uniqueness constraint on memberships table

go.mod, go.sum, internal/database/driver.go, internal/models/structures.go, internal/server/server.go, internal/server/structures_handler.go, internal/services/structure_service.go, internal/services/structure_service_test.go
Adds a new API endpoint to handle creation, getting, listing, and updating of structures.
Closes #200
=> Add new endpoint for structures

internal/authentication/credentials_service.go, internal/authentication/credentials_service_test.go, internal/authentication/session_manager.go, internal/authentication/session_manager_test.go, internal/database/driver.go, internal/models/session.go, internal/server/authentication_handler.go, internal/server/server.go, internal/services/login_service.go
Added a new route for session based login, and new unit tests for the
new services with this route.
Closes #273
=> Add route for session based login

docker-compose.yml, go.mod, go.sum, internal/middleware/authentication.go, internal/server/authentication_handler.go, internal/server/server.go, internal/services/login_service.go
Removes all references to JWT authentication.
Closes #296
=> Remove old JWT authentication code

docker-compose.yml, integration.Dockerfile, internal/server/server.go, main_integration.go
Adds a new main file and Dockerfile for starting the server in integration test mode. This mode starts the server in a "production" mode, with the addition of a new route for resetting the database.
Closes #315
=> Add integration test server configuration
